### ISSUE TITLE
How best to collaborate?

### ISSUE THREAD

**Issue by pspeter3** [sheibeck/fatecharactersheet#1]
I really like what you started with this and would love to make it successful. What can I do to help? I have experience with:

1. Web Frameworks
2. Web Tooling
3. Web Design

**Comment by sheibeck** [comment]
Hey, thanks for being interested and willing to help out. I'm not exactly sure what's even on the road map at this point. This really started out as a tool for me, but figured other folks would benefit so I keep adding little things hoping to get some traction.

On the list so far are:

1. Get google auth supported - there's been several people who refuse to use the site because they "don't like facebook."
2. I've had a request to allow someone to roll the dice in the dice tray and share the results with other people. The guy who owns the git repo for the dice roller already modified his repo to support loading an existing dice log back into a diceroller object - https://github.com/GreenImp/rpg-dice-roller
3. I need to refactor my fatesheet.js so that I have a character object and an adversary object as separate files, just to start making this thing a bit more modular for organizational/sanity purposes.
4. Find a way to get people using the site! I would love to see people adding adversaries so we can build a big library of them.
5. Add the ability to share a character (although, it's possible the adversary section could be the place to share stuff you want the community see, I'm not sure.)
6. Add social sharing functionality (pluses and thumbs and all that)

Those are just a couple things off the top of my head. I'm open to any ideas that you (or anyone has).  I can give you some more details on some of these if you feel like tackling them.

**Comment by pspeter3** [comment]
1. This seems fairly easy to support though I'm not sure what is being stored in DynamoDb
2. Can this be stored in DynamoDb?
3. Yeah, the code structure seems a bit confusing right now.
4. I think this may stem from design. The site isn't very intuitive right now.
5. Yes please!

**Comment by sheibeck** [comment]
I sussed out those first 2 items as issues with some more detail. 

Can you give me some ideas for #4 That might help make things more intuitive?  That could be some good low hanging fruit.

Ill work on what access I can give for db work

**Comment by sheibeck** [comment]
Peter, I setup a user for you in my AWS account. I just need the know the best way to email you some information for logging in.
